# Better key handling for Pi and modern terminals
set -g extended-keys on
set -g extended-keys-format csi-u
set -sg escape-time 0

# Keyboard first
setw -g mode-keys vi
set -g mouse off

# start selection with  v
bind-key -T copy-mode-vi v send -X begin-selection
# yank selection with y
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel
# Yank line
bind-key -T copy-mode-vi Y send -X copy-line

set -g renumber-windows on

# Vim style pane movement
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g set-clipboard external

# Better app behaviour
set -g focus-events on
set -g allow-rename off

# reload config
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Initialize TPM (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
