# Better key handling for Pi and modern terminals
set -g extended-keys on
set -g extended-keys-format csi-u
set -sg escape-time 0

setw -g mode-keys vi
set -g mouse on

# start selection with  v
bind-key -T copy-mode-vi v send -X begin-selection
# yank selection with y
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel
# Yank line
bind-key -T copy-mode-vi Y send -X copy-line

set -g renumber-windows on

# Vim style pane movement
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g set-clipboard external

# Better app behaviour
set -g focus-events on
set -g allow-rename off

# Appearance
set -g status on
set -g status-position bottom
set -g status-style "bg=#2e3440,fg=#d8dee9"

set -g status-left " #[fg=#88c0d0,bold]#S "
set -g status-right " #[fg=#81a1c1]%Y-%m-%d %H:%M "

set -g window-status-format " #[fg=#d8dee9]#I:#W "
set -g window-status-current-format " #[fg=@2e3440,bg=#88c0d0,bold]#I:#W "

set -g pane-border-style "fg=#4c566a"
set -g pane-active-border-style "fg=#88c0d0"

set -g message-style "bg=#3b4252,fg=#eceff4"
set -g mode-style "bg=#81a1c1,fg=#2e3440"

set -g status-justify left
set -g status-left-length 20
set -g status-right-length 40

# reload config
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Initialize TPM (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
